coml project2
vanyusha82228/tinkoff-hm2 pull request #3
Opened 2023-11-04 11:00 UTC by vanyusha82228

2023-11-12 18:11 UTC, ZhekTheDark requested changes
по поводу тестов: создай руками валидный лабиринт и проверяй на ожидаемый результат и второй тест с невалидным лабиринтом

2023-11-12 18:11 UTC, ZhekTheDark commented on src/main/java/edu/project2/inteface/Generator.java
> +package edu.project2.inteface;
лучше вынести этот интерфейс и его имплементации в отдейльный пекедж типа generator

2023-11-12 18:11 UTC, ZhekTheDark commented on src/main/java/edu/project2/inteface/Solver.java
> +package edu.project2.inteface;
лучше вынести этот интерфейс и его имплементации в отдейльный пекедж типа solver

2023-11-12 18:11 UTC, ZhekTheDark commented on src/main/java/edu/project2/DepthFirstSolver.java
> +                    break; // Нет пути
странно, что солвер не нашел корректный путь и вернул что-то

2023-11-13 09:43 UTC, vanyusha82228 commented on src/main/java/edu/project2/DepthFirstSolver.java
> +                    break; // Нет пути
а что мне с этим сделать надо?

2023-11-14 21:39 UTC, ZhekTheDark commented on src/main/java/edu/project2/DepthFirstSolver.java
> +                    break; // Нет пути
я про то, что он возвращает какой-то не пустой список и не `null`

2023-11-15 09:27 UTC, vanyusha82228 commented on src/main/java/edu/project2/DepthFirstSolver.java
> +                    break; // Нет пути
вроде поправил теперь если он не находит путь возвращает пустой лабиринт

2023-11-15 09:27 UTC, vanyusha82228 commented on src/main/java/edu/project2/DepthFirstSolver.java
> +                    break; // Нет пути
ну если я правильно понял что надо было сделать

2023-12-05 13:52 UTC, merged